### ISSUE TITLE
来个java篇好不好

### ISSUE THREAD

**Issue by LiZongqi007** [kukyxs/CoroutinesWanAndroid#3]

**Comment by kukyxs** [comment]
java 没有协程这么一说呐

**Comment by LiZongqi007** [comment]
我是说，java的工程写一个，没法对比啊





------------------&nbsp;原始邮件&nbsp;------------------
发件人: "kuky_xs"<notifications@github.com&gt;; 
发送时间: 2019年12月20日(星期五) 晚上6:00
收件人: "kukyxs/CoroutinesWanAndroid"<CoroutinesWanAndroid@noreply.github.com&gt;; 
抄送: "君不见jj"<1842355935@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [kukyxs/CoroutinesWanAndroid] 来个java篇好不好 (#3)




java 没有协程这么一说呐
