### ISSUE TITLE
使用AsyncPagedListDiffer解决刷新空白的问题

### ISSUE THREAD

**Issue by lookup-cat** [kukyxs/CoroutinesWanAndroid#4]
参考这个回答 https://stackoverflow.com/a/54442392

**Comment by kukyxs** [comment]
感谢！抽空尝试下:smile:

**Comment by kukyxs** [comment]
测试了下该方案，部分列表可行。部分不行，需要加如下代码
```kotlin
recyclerView.itemAnimator = null
```

**Comment by lookup-cat** [comment]
还会出现动画？ 会不会是DiffUtil.ItemCallback实现的问题？

**Comment by kukyxs** [comment]
有些会出现一个 `Item` 往上推的动画，有些又不会，比较奇怪，`ItemCallback` 的写法都是一致的

**Comment by lookup-cat** [comment]
有没有可能是因为缓存里的数据跟网络查询的数据有点差别？ 或者不是data class没实现equals方法？

**Comment by kukyxs** [comment]
@641571835 我再仔细调下看看，还发现一点别的问题，可能打开的方式错了

**Comment by lookup-cat** [comment]
我重新看了下 感觉这个方式也不太科学 他是监听pagelist插入时，将pagelist提交到adapter， 假如现在刷新页面触发查询，等到查询完毕后若返回空列表，那么pagelist没有触发插入事件，pagelist就不会提交到adpater。此时adapter的数据可能就是老的脏数据，是有问题的。 要解决这个问题的重点在于，要等网络查询完毕之后，再将这个已有查询结果的pagelist提交到adapter。要在paging组件上做这个感觉好像有点麻烦，还不如自己做一个分页组件
