### ISSUE TITLE
Coroutine和组件结合的生命周期不用管理的么？

### ISSUE THREAD

**Issue by KupoGu** [kukyxs/CoroutinesWanAndroid#6]

**Comment by kukyxs** [comment]
基类实现了 `CoroutineScope`

**Comment by KupoGu** [comment]
CoroutineScope 只是具备管理协程的能力，在和组件结合的时候组件的生命周期和这个绑定了吗?没做生命周期处理是不是组件生命周期结束协程还在干活？是不是要调用下cancel？
