### ISSUE TITLE
一加5T上安装了以后无法启动app

### ISSUE THREAD

**Issue by yinssh1005** [kukyxs/CoroutinesWanAndroid#7]
你好，

我是个初学者。
下载了体验版后无法在手机上启动。
系统核心是安卓10（H2OS 10.0.0），语言切了中文，权限设置成允许这些都试过了，还是闪退。

请问有什么调查方法么？

谢谢，

**Comment by kukyxs** [comment]
可能是混淆的问题，建议直接拉取项目运行
