### ISSUE TITLE
请问关于Paging3的问题

### ISSUE THREAD

**Issue by ycuwq** [kukyxs/CoroutinesWanAndroid#9]
在`HomeArtRemoteMediator`的load里面如果没有缓存的情况下，获取page的条件下`PREPEND`和`APPEND`会抛出`InvalidObjectException`异常。请问为什么不会崩溃，是哪里捕获了么。

**Comment by kukyxs** [comment]
`HomeArtRemoteMediator` 内部的数据最终通过 `flow` 返回，异常处理在 `flow` 的 `catch` 处理。具体看 `HomeFragment` 59 行

**Comment by ycuwq** [comment]
感谢回复，但是我测试了一下，在`HomeArtRemoteMediator`抛出的异常在`HomeArticleFragment`的第60行的`catch`并不会捕获，并且删除这个`catch`也并不会崩溃。

**Comment by kukyxs** [comment]
这个问题我又重新看了下代码的实现，梳理了下大概的逻辑。在 `load` 的最后数据返回的时候，其实有通过 `try..catch..` 进行异常捕获，捕获到了异常，通过 `MediatorResult.Error(e)` 进行处理。
接着可以看下 `PageFetcherSnapshot.kt` 文件内部的 `doBoundaryCall` 这个方法，这里对 `MediatorResult.Error` 进行了处理
```kotlin
when (val mediatorResult = load(coroutineScope, loadType, pagingState)) {
            is RemoteMediator.MediatorResult.Error -> {
                stateLock.withLock {
                    val errorState = Error(mediatorResult.throwable)
                    if (state.loadStates.set(loadType, true, errorState)) {
                        pageEventCh.send(LoadStateUpdate(loadType, true, errorState))
                    }
                }
            }
...
}
```
到这呢，就把抛出的异常消费了，也就不会出现崩溃的问题了

**Comment by ycuwq** [comment]
很感谢你的回复，我又翻了一下源码，在`3.0.0-alpha04`这里我没有看到有捕获异常，如果利用了`MediatorResult.Error(e)`处理问题应该会在`addLoadStateListener`看到，我这边复现的报错的异常栈是协程调用相关的问题。
我又翻了下源码和googlecodelabs的sample。发现原sample在paging版本为`3.0.0-alpha02`不会出现额外调用的LoadType.PREPEND和LoadType.APPEND`导致不会抛出异常，但是在后续的版本还是会有异常。在googlecodelabs里面也有[相同的issues](https://github.com/googlecodelabs/android-paging/issues/93)。

然后我就看到你的项目里面使用了高版本的paging虽然会抛出`InvalidObjectException`但是程序没有崩溃，所以比较好奇。我目前对协程和flow的了解还不是特别深入，所以这个问题的原因没有没有发现，但是我推测是协程的版本不同导致的处理方式不同。
> 这个问题我又重新看了下代码的实现，梳理了下大概的逻辑。在 `load` 的最后数据返回的时候，其实有通过 `try..catch..` 进行异常捕获，捕获到了异常，通过 `MediatorResult.Error(e)` 进行处理。
> 接着可以看下 `PageFetcherSnapshot.kt` 文件内部的 `doBoundaryCall` 这个方法，这里对 `MediatorResult.Error` 进行了处理
> 
> ```kotlin
> when (val mediatorResult = load(coroutineScope, loadType, pagingState)) {
>             is RemoteMediator.MediatorResult.Error -> {
>                 stateLock.withLock {
>                     val errorState = Error(mediatorResult.throwable)
>                     if (state.loadStates.set(loadType, true, errorState)) {
>                         pageEventCh.send(LoadStateUpdate(loadType, true, errorState))
>                     }
>                 }
>             }
> ...
> }
> ```
> 
> 到这呢，就把抛出的异常消费了，也就不会出现崩溃的问题了
